"""initial schema all tables

Revision ID: a41917697bda
Revises: 
Create Date: 2026-04-26 14:51:49.439071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a41917697bda'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lgus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('province', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=7), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('barangays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('lgu_id', sa.UUID(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=7), nullable=False),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=7), nullable=False),
    sa.Column('poverty_incidence_pct', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('historical_disaster_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lgu_id'], ['lgus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('lgu_id', sa.UUID(), nullable=True),
    sa.Column('barangay_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['barangay_id'], ['barangays.id'], ),
    sa.ForeignKeyConstraint(['lgu_id'], ['lgus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('disaster_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lgu_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('disaster_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('declared_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lgu_id'], ['lgus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('damage_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disaster_event_id', sa.UUID(), nullable=False),
    sa.Column('barangay_id', sa.UUID(), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('population_affected', sa.Integer(), nullable=False),
    sa.Column('casualty_count', sa.Integer(), nullable=True),
    sa.Column('structures_damaged', sa.Integer(), nullable=True),
    sa.Column('structures_destroyed', sa.Integer(), nullable=True),
    sa.Column('road_accessibility', sa.String(length=50), nullable=False),
    sa.Column('has_power', sa.Boolean(), nullable=True),
    sa.Column('has_water', sa.Boolean(), nullable=True),
    sa.Column('hours_since_last_goods', sa.Integer(), nullable=True),
    sa.Column('goods_received_qty', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('special_needs_notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['barangay_id'], ['barangays.id'], ),
    sa.ForeignKeyConstraint(['disaster_event_id'], ['disaster_events.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supply_inventory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disaster_event_id', sa.UUID(), nullable=False),
    sa.Column('goods_type', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('warehouse_latitude', sa.DECIMAL(precision=10, scale=7), nullable=False),
    sa.Column('warehouse_longitude', sa.DECIMAL(precision=10, scale=7), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('logged_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['disaster_event_id'], ['disaster_events.id'], ),
    sa.ForeignKeyConstraint(['logged_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allocations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('disaster_event_id', sa.UUID(), nullable=False),
    sa.Column('barangay_id', sa.UUID(), nullable=False),
    sa.Column('supply_inventory_id', sa.UUID(), nullable=False),
    sa.Column('quantity_allocated', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('priority_score', sa.DECIMAL(precision=5, scale=2), nullable=False),
    sa.Column('priority_rank', sa.Integer(), nullable=False),
    sa.Column('shap_explanation', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('recommended_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_confirmed_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['barangay_id'], ['barangays.id'], ),
    sa.ForeignKeyConstraint(['delivery_confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['disaster_event_id'], ['disaster_events.id'], ),
    sa.ForeignKeyConstraint(['supply_inventory_id'], ['supply_inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allocations')
    op.drop_table('supply_inventory')
    op.drop_table('damage_reports')
    op.drop_table('disaster_events')
    op.drop_table('users')
    op.drop_table('barangays')
    op.drop_table('lgus')
    # ### end Alembic commands ###
